version: '3'

services:
  database:
    image: postgres
    container_name: postgres_interview_job
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
    networks:
      - backend

networks:
  backend:
    driver: "bridge"